### ISSUE TITLE
Get new users per hour working properly in the notebook

### ISSUE THREAD

**Issue by simonw** [simonw/scrape-instances-social#3]
Current broken version:

<img width="644" alt="image" src="https://user-images.githubusercontent.com/9599/202934017-654596b0-53ef-4abf-8287-e611a92cf391.png">

Using this SQL query:
```sql
with windowed as (
  SELECT
    _commit_at as date,
    users - LAG(users) OVER (
      ORDER BY
        _commit_at
    ) AS new_users,
    users
  FROM
    item_version_detail
)
select
  date,
  100.0 * new_users / users as pct_growth,
  users,
  new_users
from
  windowed
where
  pct_growth is not null
-- First data point is negative, not sure why - makes the chart confusing
and date > '2022-11-20T01:14:46+00:00'
```

**Comment by simonw** [comment]
I was going to try this SQL instead:

```sql
select strftime('%Y-%m-%d %H:00:00', _commit_at) as hour, min(users) as users
from item_version_detail group by hour
```
https://lite.datasette.io/?url=https://scrape-instances-social.s3.amazonaws.com/counts.db#/counts?sql=select+strftime%28%27%25Y-%25m-%25d+%25H%3A00%3A00%27%2C+_commit_at%29+as+hour%2C+min%28users%29+as+users%0Afrom+item_version_detail+group+by+hour

But then I noticed @mbostock had submitted a change suggestion that fixed it like this!

<img width="604" alt="image" src="https://user-images.githubusercontent.com/9599/202934185-5504f2b5-5021-4f07-a04d-9413ae1bbbbf.png">

```javascript
Plot.plot({
  y: {
    grid: true,
    label: "New users per hour across all tracked instances"
  },
  marks: [
    Plot.ruleY([0]),
    Plot.rectY(
      points,
      Plot.windowY(
        { reduce: "difference", k: 2 },
        { x: "date", y: "users", interval: d3.utcHour }
      )
    )
  ],
  marginLeft: 100
})
```

**Comment by simonw** [comment]
https://observablehq.com/@observablehq/plot-window explains `Plot.windowY`. In particular:

> `Plot.windowY` and `Plot.windowX` are specialized [map transforms](https://observablehq.com/@observablehq/plot-map?collection=@observablehq/plot), which take a series of numeric values as input and average them (or, more generically, reduce them) over a sliding window:
>
> [...]
>
> - `k`, the width of the window, is the (integer) number of consecutive elements that will be considered for each position. k must be specified and greater than 1, otherwise the transform will throw an error.
> - `reduce`, the reducer. Defaults to mean. Describes how the k numeric values in the window are reduced to one value.

**Comment by simonw** [comment]
I'm actually not convinced this doesn't get confused by the fact that a given hour might have three measurements in it, depending on how lucky I got with the GitHub Actions "run every 20 minutes" scheduling.

I may need to combine Mike's trick with the improved SQL query I wrote after all.

**Comment by simonw** [comment]
I think switching out the query for this did the right thing:
```sql
select strftime('%Y-%m-%d %H:00:00', _commit_at) as date, min(users) as users, min(statuses) as statuses
from item_version_detail group by date
```

**Comment by mbostock** [comment]
> I'm actually not convinced this doesn't get confused by the fact that a given hour might have three measurements in it, depending on how lucky I got with the GitHub Actions "run every 20 minutes" scheduling.

In my example I was using the **line** mark, and when you use the **interval** option with the line mark, it does an implicit [bin transform](https://observablehq.com/@observablehq/plot-bin) with a default **reducer** of _first_ such that you only get the first observation for each interval (here d3.utcHour). So in this example

```js
Plot.lineY(
  points,
  Plot.windowY(
    { reduce: "difference", k: 2 },
    { x: "date", y: "users", interval: d3.utcHour }
  )
)
```

The following steps are applied:

1. The data are binned (grouped) by hour 
2. The first observation per hour (if any) is returned
3. Rolling length-two windows of hourly observations are constructed
4. The difference between the hour and previous hour is returned

You can write this more explicitly like so:

```js
Plot.lineY(
  points,
  Plot.windowY(
    {
      reduce: "difference",
      k: 2
    },
    Plot.binX(
      { y: "first" },
      { x: "date", y: "users", interval: d3.utcHour }
    )
  )
)
```

If you switch to the **rect** mark, you’ll need to apply the bin transform yourself, explicitly, because by default the **interval** option with a rect will stack instead of bin. So that’s just taking the above and replacing `lineY` with `rectY`.

```js
Plot.rectY(
  points,
  Plot.windowY(
    {
      reduce: "difference",
      k: 2
    },
    Plot.binX(
      { y: "first" },
      { x: "date", y: "users", interval: d3.utcHour }
    )
  )
)
```

Of course, it is often easier (or at least more familiar) to do this type of transformation in the SQL — just showing how you’d do it in Plot and what’s happening under the hood. Thanks for using Plot!
